### ISSUE TITLE
Exiled version of the plugin doesn't work anymore

### ISSUE THREAD

**Issue by SomeoneFrom-Somewhere** [warden161/ScpChatExtension#1]
The plugin doesn't work anymore as of the latest exiled release `6.1.0-beta2`.
![Error](https://user-images.githubusercontent.com/70498097/229655394-9ee75d27-54a0-4621-a871-de0eecc6a87e.png)

**Comment by KazanskiyMaks** [comment]
It seems to be Exiled's problem. Try to open issue there.

**Comment by SomeoneFrom-Somewhere** [comment]
Alright, well the issue is fixed in the new version of the plugin.
